// src/front-end/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {}

}

<header>
  <img src="../../assets/images/logo.svg" alt="Dev Binder">
</header>

// src/front-end/src/components/Navbar/index.tsx
import React from 'react';

import { Nav } from './styles';
import logo from '../../assets/images/logo.svg';
import { useAuth } from '../../contexts/auth';

const Navbar: React.FC = () => {
  const { signed } = useAuth();

  if (!signed) return null;

  return (
    <Nav>
      <img src={logo} alt="Dev Binder" />
    </Nav>
  );
};

export default Navbar;
